name: NodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install ionic
      run: npm install -g @ionic/cli

    - name: Build     
      run: |
        npm install
        ionic build
        
     #- name: Archive production artifacts
     # uses: actions/upload-artifact@v3
     # with:
     #   name: www
     #   path: www
        
    - name: Deploy to production 
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
          username: 'kyne'
          server: 'kyne.ovh'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './www/*'
          remote_path: '/home/kyne/fallout-www'
          args: '-o ConnectTimeout=5'
          
    - name: Init SSH
      run:  |
        mkdir /home/runner/.ssh/
        ssh-keyscan -H kyne.ovh > /home/runner/.ssh/known_hosts
        touch /home/runner/.ssh/private_key.pem
        'echo "$SSH_KEY" > /home/runner/.ssh/private_key.pem'
        chmod 400 /home/runner/.ssh/private_key.pem
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          
    - name: Deploy to production 
      run: rsync -Pav -e "ssh -i /home/runner/.ssh/private_key.pem" kyne@kyne.ovh:/www/ /fallout-www/
